name: Build & Publish Release APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

  build_desktop:
     name: Build Desktop App
     strategy:
        matrix:
           os: [ ubuntu-latest, macos-latest, windows-latest ]
     runs-on: ${{ matrix.os }}
     steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Build Desktop App
          uses: openMF/kmp-build-desktop-app-action@v1.0.0
          with:
            desktop_package_name: 'myapp'
